Nexters/ditto

components/layouts/BottomNavigation.tsx
components/layouts/Header.tsx
components/layouts/MainLayout.tsx
next.config.js
pages/_app.tsx
pages/bucketlist/[folderId].tsx
pages/bucketlist/index.tsx
pages/event/index.tsx
pages/index.tsx
pages/mypage/index.tsx
styles/theme/components/index.ts
styles/theme/foundations/colors.ts
styles/theme/foundations/fonts.ts
styles/theme/foundations/index.ts
styles/theme/index.ts
styles/theme/styles.ts

Nexters/ditto#10
- chakra theme 기본 설정을 해두었습니다.
- 대강의 레이아웃을 잡고, 라우팅을 조금 보완했습니다.
- 각 페이지에 레이아웃을 적용했습니당

feat: 레이아웃 컴포넌트 추가 및 chakra 설정 

---

hooks/useFetchBucketFolders.ts
hooks/useFetchBucketItems.ts
lib/supabase/schema.ts
lib/supabase/type.ts
package.json
pages/bucketlist/[folderId].tsx
pages/bucketlist/index.tsx
yarn.lock

Nexters/ditto#24
react-query 훅을 구현하고 임시로 적용했습니다! (아직 데이터가 없어서..) 
제가 스키마를 제너레이팅하니 뭔가 이상하게 사라져서 ㅠㅠ 임의로 추가해두었는데요!! 내일 방법을 다시 한 번 여쭤보겠습니다..!!

feat: react-query 훅 임시 적용

---

components/bucketFolder/BucketFolderItem.tsx
components/bucketFolder/BucketFolderList.tsx
components/bucketItem/BucketItem.tsx
components/bucketItem/BucketItemList.tsx
components/modal/AddBucketFolderModal.tsx
components/modal/UpdateBucketFolderModal.tsx
components/modal/UpdateBucketItemModal.tsx
hooks/useMutateBucketFolders.ts
hooks/useMutateBucketItems.ts
pages/bucketlist/[folderId].tsx
pages/bucketlist/index.tsx

Nexters/ditto#24
Nexters/ditto#25

feat: 버킷리스트 컴포넌트 분리, 훅 추가 

---

package.json

Nexters/ditto#
- 저희가 yarn berry로 처음에 환경설정 해서 그런지 install이 안되어있었나 봅니다.
- prepare로 스크립트 이름을 변경해서 동작하게 변경했습니다.

fix: husky install 안되던 것 수정

---

components/buttons/BaseButton.tsx
components/inputs/ContentTextarea.tsx
components/inputs/TitleITextarea.tsx
components/inputs/TitleTextarea.tsx
components/modals/AddBucketFolderModal.tsx
components/modals/UpdateBucketItemModal.tsx

Nexters/ditto#
textarea 컴포넌트 구현을 수정하였습니다!! (forwardRef로 할까하다가 굳이 안해도될것같아서 요렇게 했습니당 ㅎㅎ)

fix: content/title textarea 컴포넌트 수정

---

components/buttons/BaseButton.tsx

Nexters/ditto#
스타일만 바뀌고 기능이 안막혀있어서 8ㅅ8 ;; 수정하였습니다!!

fix: button isDisabled 속성 추가

---

components/bucketFolder/BucketFolderItem.tsx
components/bucketItem/BucketItem.tsx
components/bucketItem/BucketItemList.tsx
components/buttons/PawButton.tsx
components/modals/AddBucketFolderModal.tsx
components/modals/UpdateBucketFolderModal.tsx
components/modals/UpdateBucketItemModal.tsx
hooks/bucketlist/useFetchBucketFolderById.ts
hooks/bucketlist/useMutateBucketFolders.ts
hooks/bucketlist/useMutateBucketItems.ts
lib/supabase/apis/bucketlist/index.ts
lib/supabase/apis/bucketlist/type.ts
pages/bucketlist/[folderId].tsx

Nexters/ditto#
API들을 연동해두었는데요.. 지금보니 mutation을 너무 여러개 만든것도 좀 귀찮고, 쿼리키 invalidate하는 것도 좀 수정해야하고.. 
일단 기능 구현을 해두고, 수정할 예정입니다!!

feat: 버킷폴더/아이템 API 연동

---

components/bucketItem/BucketItem.tsx
components/bucketItem/BucketItemList.tsx
components/icons/TrashCanIcon.tsx
components/modals/UpdateBucketFolderModal.tsx
components/modals/UpdateBucketItemModal.tsx

Nexters/ditto#82
버킷 폴더/아이템 삭제 기능을 추가하였습니다.

feat: 버킷 삭제 API 추가

---

components/bucketFolder/BucketFolderList.tsx
components/bucketItem/BucketItemList.tsx
components/bucketItem/EmptyItem.tsx
components/loading/PartialLoader.tsx
hooks/bucketlist/useFetchBucketFolderById.ts
hooks/bucketlist/useFetchBucketFolders.ts
hooks/bucketlist/useFetchBucketItems.ts
pages/bucketlist/[folderId].tsx

Nexters/ditto#82
로딩이 너무 깜빡거려서.. 최소높이를 주고, 로더를 추가했습니다!
리액트 쿼리는 아직 좀 더 공부해봐야해서 실험적으로 이래저래 테스트해보고있습니다!

fix: 로딩 개선

---

components/groupMenu/GroupMenu.tsx
pages/mypage/index.tsx

Nexters/ditto#75
- 피그마에 나온대로 마크업 작업했습니다.

feat: 그룹 메뉴 마크업

---

components/layouts/BottomNavigation.tsx

Nexters/ditto#85
하단바 마크업 진행했습니다

feat: 하단바 마크업

---

pages/_app.tsx

Nexters/ditto#
https://tanstack.com/query/v4/docs/react/guides/ssr
위 문서에 따라 이슈를 수정하였습니다~!

fix: react-query 설정

---

components/modals/CreateGroupModal.tsx
components/modals/InviteMemberModal.tsx

resolve Nexters/ditto#61
- 초대하기 모달, 새 그룹 만들기 모달 마크업 진행했습니다.

feat: 초대하기 모달, 새 그룹 만들기 모달 마크업

---

components/modals/CreateGroupModal.tsx

resolve Nexters/ditto#121
- 새 그룹 생성 후에 별 다른 동작이 없다는 피드백으로 인해 추가합니다.

feat: 새 그룹 생성 시 토스트 + 리다이렉션 추가

---

components/bucketItem/BucketItemInput.tsx
components/modals/BaseModal.tsx

Nexters/ditto#
- modal의 autofocus를 제거
- input의 border style 수정

fix: input, modal 스타일 이슈 수정

---

components/memberList/MemberList.tsx
hooks/member/useFetchMemberList.ts
lib/supabase/apis/member.ts

Nexters/ditto#
- 나 자신이 그룹 멤버 리스트에 없는건 이상한 것 같다고 생각되어 추가시킵니다.

fix: useFetchMemberList에서 나 자신 포함되도록 수정

---

components/bucketItem/BucketItemList.tsx
components/bucketItem/ConditionalRabbitIcon.tsx

Nexters/ditto#
로더를 둘러싼 wrapper에 적절한 height을 주지않으면 화면이 너무 들썩거려서.. height을 주었습니당

fix: loading style 수정

---

hooks/bucketlist/useChangeCreatorIdToName.ts

Nexters/ditto#
- 머지하는 과정에서 문제가 생겨 이를 수정합니다.
- 추가로 changeCreatorIdToName이 string을 무조건 반환하도록 수정합니다.
- 선머지하겠습니다. 피드백은 이후 남겨주셔도 감사합니다 :)

hotfix: 빌드 에러 실패 수정

---

pages/event/index.tsx
utils/date.ts

Nexters/ditto#119
- 오늘 칩버튼은 startDate와 endDate 닐짜에 오늘이 포함될 때 나오도록 수정했습니다.

fix: 오늘 칩버튼이 오늘에 해당될 때 나오도록 변경

---

components/bucketFolder/BucketFolderList.tsx
components/icons/PlusWhiteIcon.tsx
components/toasts/Toast.tsx
hooks/bucketlist/useMutateBucketFolders.ts
hooks/bucketlist/useMutateBucketItems.ts
hooks/shared/useCustomToast/index.tsx

Nexters/ditto#
docs에 있는 이슈들을 처리하였습니당.

fix: toast 추가, add bucket 마크업 수정 

---

components/modals/bucketList/UpdateBucketItemModal.tsx

Nexters/ditto#
- #139 에서 잘못 수정한게 있어 급하게 수정합니다 ;.;

hotfix: 버킷 아이템 모달에서 잘못 고친거 수정

---

components/modals/EventModal.tsx

Nexters/ditto#
- 일정 수정 모달을 esc키로 끄고 일정 추가버튼을 빠르게 누르면 이전에 선택했던 일정 수정 모달이 뜨는 버그를 수정했습니다

fix:  일정 수정 모달을 esc키로 끄고 일정 추가버튼을 누르면 이전에 선택했던 일정 수정 모달이 뜨는 버그 수정

---

components/modals/EventModal.tsx
lib/confetti/index.ts
package.json
pages/_app.tsx
pages/event/index.tsx
yarn.lock

Nexters/ditto#
- 그룹 내 첫 일정 추가시에 토끼와 당근이 섞인 confetti가 나오도록 적용했습니다

feat: 그룹 내 첫 일정 추가시에 토끼와 당근이 섞인 confetti가 나오도록 적용

---

components/loading/PartialLoader.tsx

fix: loader 색 수정

---

store/useUser.ts

Nexters/ditto#74
인증 실패 여부를 체크하지 않아서 급하게 체크합니다

hotfix: supabase 로그인 실패 체크

---

pages/event/index.tsx

Nexters/ditto#100
- 일정 hover, active 스타일을 적용했습니다.

style: 일정 hover, active 스타일 적용

---

components/bucketItem/BucketItem.tsx
components/bucketItem/BucketItemList.tsx
components/ga/GoogleAnalytics.tsx
hooks/bucketlist/useFetchBucketItems.ts
lib/supabase/apis/bucketlist/index.ts
package.json
pages/_app.tsx
pages/event/index.tsx
utils/date.ts
yarn.lock

Nexters/ditto#
사용하면서 몇 가지 수정하고 싶은 부분을 수정했습니다.
- 버킷리스트
- 완료된 버킷아이템을 밑으로 내리고, 최근에 생성한게 맨 위로 올라오도록 변경했습니다.
- 완료했을때 토스트를 추가했습니다.
- 일정
- "다가오는"이라는 문구의 어색함이 느껴져서, 다가오는 일정, 지난 일정 -> 예정된, 완료된 일정으로 변경했습니다.
- 기간이 긴 일정의 경우 오늘 뱃지 표시가 되지 않아 수정했습니다.
- 기타
- vercel analytics를 추가하려합니다.
- https://vercel.com/docs/concepts/analytics

fix: 몇 가지 개선

---

hooks/useFirebaseMessaging.ts
pages/_app.tsx
public/favicon/site.webmanifest

Nexters/ditto#
iOS 모바일에선 아예 페이지가 제대로 노출되지 않아 바로 머지합니다.
- Notification 및 생성자 함수가 모바일에선 정상적으로 동작하지 않더라구요.
- 그래서 serviceWorker를 사용하는 방식으로 기능을 수정했습니다.
- public/favicon/site.webmanifest 에 name, short_name이 비어있어서 그런지 앱 설치 안내가 안떴습니다.
- 그래서 이를 수정했습니다.

bugfix: 알림 기능 추가하면서 발생한 버그 수정

---

.gitignore
next.config.js
package.json
sentry.client.config.ts
sentry.edge.config.ts
sentry.server.config.ts
yarn.lock

Nexters/ditto#
큰 문제는 없어보여 바로 머지합니닷!
- 에러 났는지 확인하기 위해 sentry를 ~이제야~ 연동합니다
- sentry next.js 가이드 문서 참고하고 거의 달라진 건 없습니다;
- https://docs.sentry.io/platforms/javascript/guides/nextjs/
- sentry 프로젝트가 2명 이상이 되면 과금되는 구조라 일단 제가 트래킹하고 있겠습니다😅

feat: sentry 연동
